version: '3'

services:
  nginx:
    image: saimon46/wedding-website-nginx
    restart: always
    ports:
      - '80:80'
    depends_on:
      - api

  api:
    image: saimon46/wedding-website-api
    volumes:
      - /app/node_modules
      - ./api:/app

  client:
    image: saimon46/wedding-website-client
    volumes:
      - /app/node_modules
      - ./client:/app